jobs:
  codecov:
    if: github.repository == 'elki-project/elki'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Code coverage
      run: ./gradlew --no-daemon clean test :codeCoverageReport -Pjacoco
    - continue-on-error: true
      name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v3
name: Code coverage
on:
  repository_dispatch:
    types: trigger-ga___codecov.yml
